on:
  - push

jobs:
  build-app-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: pnpm install
      - run: pnpm build